// このファイルは自動生成されています。直接編集しないでください。

export const tokenDesignTokens = {
  'border-radius': {
    none: 0,
    xs: 2,
    sm: 4,
    md: 6,
    lg: 8,
    xl: 12,
    '2xl': 16,
    '3xl': 24,
    full: 9999,
  },
  opacity: {
    '0': 0,
    '25': 25,
    '50': 50,
    '75': 75,
    '100': 100,
  },
  spacing: {
    none: 0,
    md: 12,
    sm: 8,
    xs: 4,
    lg: 14,
    xl: 16,
    '2xl': 24,
    '3xl': 32,
    '4xl': 40,
    '5xl': 48,
    '6xl': 56,
    '2xs': 2,
  },
  Elevation: {
    Styles: {
      elevation2: {
        color: 'rgba(0, 0, 0, 0.15)',
        type: 'dropShadow',
        x: 0,
        y: 2,
        blur: 4,
        spread: 0,
      },
      elevation4: {
        color: 'rgba(0, 0, 0, 0.15)',
        type: 'dropShadow',
        x: 0,
        y: 4,
        blur: 8,
        spread: 0,
      },
      elevation8: {
        color: 'rgba(0, 0, 0, 0.15)',
        type: 'dropShadow',
        x: 0,
        y: 8,
        blur: 12,
        spread: 0,
      },
      elevation12: {
        color: 'rgba(0, 0, 0, 0.25)',
        type: 'dropShadow',
        x: 0,
        y: 12,
        blur: 20,
        spread: 0,
      },
    },
  },
  Button: {
    'Size md - line-height line': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Bold',
      lineHeight: '113.4%',
      fontSize: 14,
      letterSpacing: '0%',
      paragraphSpacing: 0,
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    'Size sm - line-height line': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Bold',
      lineHeight: '113.4%',
      fontSize: 12,
      letterSpacing: '0%',
      paragraphSpacing: 0,
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  Input: {
    'Size md - line-height line': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Regular',
      lineHeight: '125%',
      fontSize: 16,
      letterSpacing: '0%',
      paragraphSpacing: 0,
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    'Number Size md - line-height line': {
      fontFamily: 'Lato',
      fontWeight: 'Regular',
      lineHeight: '125%',
      fontSize: 16,
      letterSpacing: '0%',
      paragraphSpacing: 0,
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  TextArea: {
    'Size md': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Regular',
      lineHeight: '150%',
      fontSize: 16,
      letterSpacing: '0%',
      paragraphSpacing: 0,
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  'Checkbox & Radio': {
    'Size md': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Regular',
      lineHeight: '130%',
      fontSize: 16,
      letterSpacing: '0%',
      paragraphSpacing: 0,
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  fontFamilies: {
    'biz-udpgothic': 'BIZ UDPGothic',
    lato: 'Lato',
  },
  lineHeights: {
    '0': '113.4%',
    '1': '125%',
    '2': '150%',
    '3': '130%',
  },
  fontWeights: {
    'biz-udpgothic-0': 'Bold',
    'biz-udpgothic-1': 'Regular',
    'lato-2': 'Regular',
  },
  fontSize: {
    '0': 12,
    '1': 14,
    '2': 16,
  },
  letterSpacing: {
    '0': '0%',
  },
  paragraphSpacing: {
    '0': 0,
  },
  textCase: {
    none: 'none',
  },
  textDecoration: {
    none: 'none',
  },
  paragraphIndent: {
    '0': '0px',
  },
} as const;
