// このファイルは自動生成されています。直接編集しないでください。

export const tokenDesignTokens = {
  'border-radius': {
    none: '0',
    xs: '2px',
    sm: '4px',
    md: '6px',
    lg: '8px',
    xl: '12px',
    '2xl': '16px',
    '3xl': '24px',
    full: '9999px',
  },
  opacity: {
    '0': '0',
    '25': '25',
    '50': '50',
    '75': '75',
    '100': '100',
  },
  spacing: {
    none: '0',
    md: '12px',
    sm: '8px',
    xs: '4px',
    lg: '14px',
    xl: '16px',
    '2xl': '24px',
    '3xl': '32px',
    '4xl': '40px',
    '5xl': '48px',
    '6xl': '56px',
    '2xs': '2px',
  },
  Elevation: {
    Styles: {
      elevation2: {
        color: '#00000026',
        type: 'dropShadow',
        x: '0',
        y: '2px',
        blur: '4',
        spread: '0',
      },
      elevation4: {
        color: '#00000026',
        type: 'dropShadow',
        x: '0',
        y: '4px',
        blur: '8',
        spread: '0',
      },
      elevation8: {
        color: '#00000026',
        type: 'dropShadow',
        x: '0',
        y: '8px',
        blur: '12',
        spread: '0',
      },
      elevation12: {
        color: '#00000040',
        type: 'dropShadow',
        x: '0',
        y: '12px',
        blur: '20',
        spread: '0',
      },
    },
  },
} as const;
