// このファイルは自動生成されています。直接編集しないでください。

export const tokenDesignTokens = {
  'border-radius': {
    none: '0px',
    xs: '2px',
    sm: '4px',
    md: '6px',
    lg: '8px',
    xl: '12px',
    '2xl': '16px',
    '3xl': '24px',
    full: '9999px',
  },
  opacity: {
    '0': 0,
    '25': 25,
    '50': 50,
    '75': 75,
    '100': 100,
  },
  spacing: {
    none: '0px',
    md: '12px',
    sm: '8px',
    xs: '4px',
    lg: '14px',
    xl: '16px',
    '2xl': '24px',
    '3xl': '32px',
    '4xl': '40px',
    '5xl': '48px',
    '6xl': '56px',
    '2xs': '2px',
  },
  Elevation: {
    Styles: {
      elevation2: {
        color: '#00000026',
        type: 'dropShadow',
        x: 0,
        y: 2,
        blur: 4,
        spread: 0,
      },
      elevation4: {
        color: '#00000026',
        type: 'dropShadow',
        x: 0,
        y: 4,
        blur: 8,
        spread: 0,
      },
      elevation8: {
        color: '#00000026',
        type: 'dropShadow',
        x: 0,
        y: 8,
        blur: 12,
        spread: 0,
      },
      elevation12: {
        color: '#00000040',
        type: 'dropShadow',
        x: 0,
        y: 12,
        blur: 20,
        spread: 0,
      },
    },
  },
  Button: {
    'Size md - line-height line': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Bold',
      lineHeight: '113.4%',
      fontSize: '0.875rem',
      letterSpacing: '0%px',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    'Size sm - line-height line': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Bold',
      lineHeight: '113.4%',
      fontSize: '0.75rem',
      letterSpacing: '0%px',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  Input: {
    'Size md - line-height line': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Regular',
      lineHeight: '125%',
      fontSize: '1rem',
      letterSpacing: '0%px',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    'Number Size md - line-height line': {
      fontFamily: 'Lato',
      fontWeight: 'Regular',
      lineHeight: '125%',
      fontSize: '1rem',
      letterSpacing: '0%px',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  TextArea: {
    'Size md': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Regular',
      lineHeight: '150%',
      fontSize: '1rem',
      letterSpacing: '0%px',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  'Checkbox & Radio': {
    'Size md': {
      fontFamily: 'BIZ UDPGothic',
      fontWeight: 'Regular',
      lineHeight: '130%',
      fontSize: '1rem',
      letterSpacing: '0%px',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  fontFamilies: {
    'biz-udpgothic': 'BIZ UDPGothic',
    lato: 'Lato',
  },
  lineHeights: {
    '0': '113.4%',
    '1': '125%',
    '2': '150%',
    '3': '130%',
  },
  fontWeights: {
    'biz-udpgothic-0': 'Bold',
    'biz-udpgothic-1': 'Regular',
    'lato-2': 'Regular',
  },
  fontSize: {
    '0': '0.75rem',
    '1': '0.875rem',
    '2': '1rem',
  },
  letterSpacing: {
    '0': '0%px',
  },
  paragraphSpacing: {
    '0': '0px',
  },
  textCase: {
    none: 'none',
  },
  textDecoration: {
    none: 'none',
  },
  paragraphIndent: {
    '0': '0px',
  },
} as const;
